name: umbra

packages:
  - apps/**
  - packages/**

scripts:
  analyze:
    exec: flutter analyze .
    description: "Run flutter analyze"
  test:
    exec: flutter test
    no-select: true
    description: "Run flutter test"
