name: Melos Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.29.3

      - name: Activate Melos
        uses: bluefireteam/melos-action@v3
        with:
          run-bootstrap: true

      - name: Run tests
        run: melos run test
